name: smarttek2
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - scipy
  - pillow
  - matplotlib
  - imageio     # <-- add this
  - pip
  - pip:
      - streamlit
      - pydicom
      - gdcm
      - pylibjpeg
      - pylibjpeg-libjpeg
      - pylibjpeg-openjpeg